name: Build Kivy APK

on:
  push:
    branches: [ "main" ] # Or whatever your main branch is called

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.34 # Pin cython version for stability
        pip install git+https://github.com/kivy/pyjnius.git
        sudo apt-get update
        sudo apt-get install -y \
          libncurses-dev \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          cmake

    - name: Configure for Android Build
      run: |
        # Add a specific, stable build-tools version to the spec file
        # This helps avoid license prompts and missing tool errors in CI environments
        echo "" >> buildozer.spec
        echo "android.build_tools = 30.0.3" >> buildozer.spec

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: yt-downloader-apk
        path: bin/*.apk
